#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
pushd "$HOME"

# Now, we can init all submodules
echo "Init submodules"
yadm submodule update --recursive --init
